name: myblog
title: blog for java and life
description: this is my private notebook
tags:
  - life
  - java
  - travel
  - note
  - mood
email: mrwhite777@163.com
disqus_username: 
show_hero: false
paginate: 12
